Basic clean option for archive

diff --git a/goproexif b/goproexif
--- a/goproexif
+++ b/goproexif
@@ -43,6 +43,7 @@ readonly HELP_TEXT="Available Options:
 -i --import
 -p --process
 -a --archive
+--clean
 --config:
 --debug
 --setup
@@ -72,6 +73,8 @@ setup=false
 debug=false
 import=false
 process=false
+archive=false
+clean=false
 sourceopt=""
 targetopt=""
 copyrightopt=""
@@ -264,6 +267,53 @@ function _archive_media()
   _info "Finished media archive"
 }
 
+function _clean_media()
+{
+  _info "Cleaning Source Media..."
+  _info "Source: "$source
+
+  # Find first image file to get camera model and serial
+  firstmedia=$(find -E . -regex '.*\.(JPG|MP4|360)' | head -n 1)
+  _info "First Media: "$firstmedia
+
+  # Camera model name
+  camera=$(exiftool -Model -s -s -s "${firstmedia}"\
+  -api 'Filter=s/HERO10 Black/GoPro_Hero10/g;'\
+'s/HERO9 Black/GoPro_Hero9/g;'\
+'s/HERO8 Black/GoPro_Hero8/g')
+
+  # Last 4 digits of serial number
+  serial=$(exiftool -CameraSerialNumber -s -s -s "${firstmedia}")
+  timestamp=$(date +%Y%m%d%H%M%S)
+
+  _info "Camera: "$camera
+  _info "Serial: "${serial:(-4)}
+  _info "Time: "$timestamp
+
+  # Only proceed if we just finished archiving this media
+  if [ "$archive" = true ]; then
+    rm -rf $source/* || {
+      # Cleanup failed
+      _error "Cleaning ${source} failed!"
+      exit 1
+    }
+  else
+    _error "Will not clean ${source} without prior archive"
+    _error "Run options --archive and --clean together"
+    exit 1
+  fi
+
+  tar --totals -zcvf "${archivedir}"/"${archivename}".tar.gz $source || {
+    # Archive failed
+    _error "Archive creation failed!"
+    exit 1
+  }
+
+  _info "Finished cleanup tasks"
+}
+
+
+
 # Enable color output
 autoload colors
 colors
@@ -278,6 +328,7 @@ zparseopts -D -E -F -A opts - \
             i -import \
             p -process \
             a -archive \
+            -clean \
             -config: \
             -debug \
             -setup \
@@ -319,6 +370,10 @@ for key val in "${(kv@)opts}"; do
     -a|--archive)
       # Perform archive tasks
       archive=true
+    ;;
+    --clean)
+      # Perform archive tasks
+      clean=true
     ;;
     --setup)
       # Perform setup tasks
@@ -442,6 +497,9 @@ if [ "$process" = true ]; then
 fi
 if [ "$archive" = true ]; then
   _archive_media
+fi
+if [ "$clean" = true ]; then
+  _clean_media
 fi
 
 ) 2>&1 | eval ${output}
